{% set version = "3.19.1" %}

package:
  name: libdap4
  version: {{ version }}

source:
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 487c86ad95b45a83e9f0fc09b69107f6b035d7373c2a7a717532b6e31b1cb6ee

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - flex
    - bison
    - libxml2 2.9.*
    - curl
    - util-linux  # [linux]
  run:
    - libxml2 2.9.*
    - curl
    - util-linux  # [linux]

test:
  commands:
    - dap-config --version
    - conda inspect linkages -p $PREFIX libdap4  # [not win]
    - conda inspect objects -p $PREFIX libdap4  # [osx]

about:
  home: http://www.opendap.org
  license: GNU LGPL
  license_file: COPYING
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4.'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
