{% set version = "3.18.0" %}

package:
  name: libdap4
  version: {{ version }}

source:
  fn: version-{{ version }}.tar.gz
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 373c60cf2c5c9eaf598558167aedbc3ef9a0d9b652dfbd96b4725637cf03f628

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - flex
    - bison
    - libxml2
    - curl
  run:
    - libxml2
    - curl

test:
  commands:
    - dap-config --version
    #- conda inspect linkages -p $PREFIX libdap4  # [not win]
    #- conda inspect objects -p $PREFIX nco  # [osx]


about:
  home: http://www.opendap.org
  license: GNU LGPL
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4.'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
