{% set version = "3.19.0" %}

package:
  name: libdap4
  version: {{ version }}

source:
  fn: libdap4-{{ version }}.tar.gz
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 226ac2ab3167dab02d35111969c1ae31bb014cf738a1531f4cb42cb8509381cd

build:
  number: 2
  skip: True  # [win]
  run_exports:
    # no ABI lab entry.  Going with minor pinning based on past conda-forge pinning.
    - {{ pin_subpackage('libdap4', max_pin='x.x') }}

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libcurl
    - libxml2
    - libuuid
    - libcurl
    - flex
  run:
    # libxml2 removed here because package has run_exports for itself
    #    https://github.com/AnacondaRecipes/libxml2-feedstock/pull/2
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - libxml2 2.9.*
    - curl

test:
  commands:
    - dap-config --version

about:
  home: http://www.opendap.org
  license: GNU LGPL
  license_file: COPYING
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4.'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
    - msarahan
