travis:
  secure:
    BINSTAR_TOKEN: eOz0un5X2hlfAYK+MsrSCMsAWuVHZ1TAptyOJD2ozkvwFS43T+yFUHQRXDeDS5rOm951NyPkPWP5oyjiH87ObrA7Ui1vkfj85sj9RcUdErKTjXlH9Ji+c1VFn4dD/9KPulGtai4HUDUn7BVlr1jh9vTNOFV20qBn274qfr0wyJIM4B+P1Y/VByJhKJEwwSZi5qACwsdOD+sJ8+wzVSWs/9Xzb6ECPjtlb/QokplLgQX5eQ6NzWzWAxqNKDnR+/HYlEaM8VOlKYYgPGp/3CapGHK+hDMm/abRx5jIv6SY8we1aroCkdFF536jG0solT7u0uynuKjhLWLVxa2IlTzcrLwq0pis5p5awbs48k9qSO73ZBBqq2ONZP7IcbFCyljxW+bfVtwC4uwT5SOYWhWde/nLhajmoPUkvJk+0zwHb/w53cUSOYLXWt9gFI0RRGwasGKVMut5MArsJDJstUBy5MMwZiOl2wmVxkueyZO4VQBgJJiE1LPIet8DUCOa1auNNKx0968oCComiFOS5vYKUI1l2PRETT+naVh+Isj8DEGUmA71btApVUzVIuQoH4d/Om8+oTBgxSi3VDzrWPmW7k7U0GVz+72aZDij92/OHnvwui/+O2+HOJ1eBfRj9e21CfEBtnQsg9lxNrnxpUSqe0giR1UZXBFdjcuVSxRYKDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
