travis:
  secure:
    BINSTAR_TOKEN: wHanQz4os5NLMtU/cS4hPo10ykDRcHsaE6dBh8BKXWQmGtI/qTwCFJO6853CqK7q6nxaI5TAPFpKw/qL1Ym6LP7oEtBvB+qM3L34qySy5a2rK6NpcHfL6H1xURVnUUCw9XbWBaqrfj7dKDC9s4xbwPNnvCFEO+a5MpZcqp3eVrqKkXZ1xL6CxtI5/sR7GIqUdGswzbIVLh01ejbzi5Rb2Mz0AR7TtzbwF+MNjCr8/wOX5ROR18KJcLFLPORctGcLgKQ1SkHgMNXgzEIN7T6FhJxHf2cG4iQgW2CucuVyRlRjABK2ZqyWMdA8gdtPw0b57RIxmSZqw4iSC+oKnPPDyjnT7jHKmA8J/vRPjaYDwNOuissEFEFPiHHAwqU5PgjWaCwms/uoshA0P8c4g3cymdAhNfuN16u/Gxd6Jmgy7zZ5RVxSyVJTOflQ6pAh1KWMeHq2SkX1aiAGy+402fq/bTXODZYZba/ywpYu4wwVXaCknmD8YciY3pSnI23Q0tAPiKkm5Y9kLJWBMREzEIwiV2FHB208FQlSjmzCBtCU8ydD4THd3WtusRdF+u/v4XD85dPUGpNjsuxUvOvsWLNDLzug7a6QI63DHy60xCdaatdfcIl32OGrIaIdAyGXCzbwMBCCTM3H1Pesdrkxubo5VHtsC0JZQ4a7982D722GpWY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
